# Generated by Django 6.0.6 on 2026-06-22 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(unique=True, verbose_name='Номер стола')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название стола')),
                ('capacity', models.IntegerField(verbose_name='Вместимость (чел)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Стол',
                'verbose_name_plural': 'Столы',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('client_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('guests_count', models.IntegerField(verbose_name='Количество гостей')),
                ('date', models.DateField(verbose_name='Дата бронирования')),
                ('time', models.TimeField(verbose_name='Время бронирования')),
                ('duration_hours', models.IntegerField(default=2, verbose_name='Длительность (часов)')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтверждена'), ('canceled', 'Отменена'), ('completed', 'Завершена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.table', verbose_name='Стол')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
